# Generated by Django 5.0.1 on 2024-01-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer_image_url_alter_posts_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='child_topic_id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='parent_topic_id',
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_topics', to='main.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_type',
            field=models.IntegerField(choices=[(0, 'Parent'), (1, 'Child')], default=0),
        ),
    ]
