# Generated by Django 5.0.1 on 2024-01-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_topic_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='parent_topic',
            new_name='parent_topic_id',
        ),
    ]
