# Generated by Django 5.0.1 on 2024-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_parent_topic_topic_parent_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
