# Generated by Django 5.0.1 on 2024-01-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_question_topic_question_subtopic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subtopic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_subtopic', to='main.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_topic', to='main.topic'),
        ),
    ]
