# Generated by Django 5.0 on 2024-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_question_subtopic_id_alter_question_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
