# Generated by Django 5.0 on 2024-01-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_user_id_answer_user_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_i',
            new_name='user_id',
        ),
    ]
