# Generated by Django 5.0 on 2024-01-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
